version: "3.7"
services:
  instream-tenant-server:
    image: instream-tenant-server:latest
    container_name: instream-tenant-server
    ports:
      - "8080:8080"
    environment:
      SERVER_MODE: dev
    env_file:
      - .env
    networks:
      mynetwork:
        ipv4_address: 172.20.0.2

  nginx-rtmp:
    container_name: nginx-rtmp
    image: nginx-rtmp
    ports:
      - 1936:1935
      - 8081:80
      - 8443:443
    environment:
      - HTTP_PORT=80
      - RTMP_PORT=1935
    volumes:
      - /Users/jangseongho/Documents/developers/4seasons/nginx-rtmp/hls:/opt/data/hls
    env_file:
      - .env
    networks:
      mynetwork:
        ipv4_address: 172.20.0.3

  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: redis
    labels:
    - "name=redis"
    - "mode=standalone"
    ports:
    - "6379:6379"
    networks:
      mynetwork:
        ipv4_address: 172.20.0.4

  mariadb:
    container_name: "mariadb"
    image: mariadb:10
    restart: always
    ports:
    - "3307:3306"
    volumes:
    - "./mariadb/conf.d:/etc/mysql/conf.d"
    - "./mariadb/data:/var/lib/mysql"
    environment:
      MARIADB_DATABASE: ${MARIA_DATABASE}
      MARIADB_USER: ${MARIA_USERNAME}
      MARIADB_PASSWORD: ${MARIA_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIA_ROOT_PASSWORD}
    networks:
      mynetwork:
        ipv4_address: 172.20.0.5

networks:
  mynetwork:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
