version: "3.7"
services:
  instream-tenant-server:
    image: instream-tenant-server:latest
    container_name: instream-tenant-server
    ports:
      - 8080:8080
    environment:
      SERVER_MODE: dev
    env_file:
      - .env
  instream-media-server:
    image: instream-media-server:latest
    container_name: instream-media-server
    volumes:
      - /Users/jangseongho/Documents/developers/4seasons/nginx-rtmp/hls-data:${HLS_PATH}
      - /Users/jangseongho/Documents/developers/4seasons/nginx-rtmp/log/hls:/var/log/hls
    ports:
      - "1935:1935"
      - "80:80"
    env_file:
      - .env

  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: redis
    labels:
    - "name=redis"
    - "mode=standalone"
    ports:
    - 6379:6379

  mariadb:
    container_name: "mariadb"
    image: mariadb:10
    restart: always
    ports:
    - 3307:3306
    volumes:
    - "./mariadb/conf.d:/etc/mysql/conf.d"
    - "./mariadb/data:/var/lib/mysql"
    environment:
      MARIADB_DATABASE: ${MARIA_DATABASE}
      MARIADB_USER: ${MARIA_USERNAME}
      MARIADB_PASSWORD: ${MARIA_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIA_ROOT_PASSWORD}