spring:
  r2dbc:
    url: r2dbc:mariadb://${MARIA_IP}:${MARIA_PORT}/${MARIA_DATABASE}?useSSL=false&serverTimezone=UTC
    username: ${MARIA_USERNAME}
    password: ${MARIA_PASSWORD}
  data:
    redis:
      host: ${REDIS_IP}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  webflux:
    base-path: /api

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  model-and-view-allowed: true

logging:
  level:
    org.springframework.web: DEBUG
    org.springdoc: DEBUG
